name: car_booking
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  google_places_flutter: ^2.0.6
  maps_places_autocomplete: ^0.0.2
  # http: ^1.1.0
=======
  geocoding: ^2.1.0
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
>>>>>>> 4be4f02211179efa60f718e0e6eb04e1afb8ffbd
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/logo.png
    - img/truck.png
    - img/QT.jpeg

  
